eureka:
  instance:
    hostname: localhost
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka
server:
  port: 8040

spring:
  application:
    name: ressource
  config:
    import: optional:configserver:http://localhost:8888
  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://localhost:5432/projets
    username: postgres
    password: 1234
  jpa:
    hibernate:
         ddl-auto: create
    database-platform: org.hibernate.dialect.PostgreSQLDialect

#application:
#  config:
#    taches-url: http://localhost:8070/api/taches